[phases.install]
cmds = [
  'NODE_ENV=development pnpm i --frozen-lockfile',  # Dev deps pro build
]

[phases.build]
cmds = [
  'pnpm run build:client',  # Vite -> dist/
  'pnpm run build:server'   # TSC server -> dist/server/
]

[start]
cmd = 'node dist/server/app.js'  # Path correto: app.ts -> app.js em dist/server